### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by chuwy** [snowplow/scala-forex#103]

**Comment by chuwy** [comment]
We forgot Sonatype credentials! @ninjabear can you tell why `+bintraySyncMavenCentral` tries to publish artifacts on sonatype? https://travis-ci.org/snowplow/scala-forex/jobs/193741915#L930

**Comment by ninjabear** [comment]
Hey @chuwy ! Yes, it's not possible to push artifacts directly to maven central, mavencentral "pulls" artifacts from a set of approved places - sonatype is one of them (so we push to sonatype, and then mavencentral will pick it up from there)

**Comment by chuwy** [comment]
Thanks. 

I created ticket for them https://github.com/snowplow/scala-forex/issues/111
